name: Release and Publish to NPM

on:
  push:
    tags:
      - 'v*' # Trigger on version tags like v1.0.0, v1.2.3, etc.

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm test
        continue-on-error: true # Continue even if tests fail (since test script currently just echoes)

      - name: Build the project
        run: pnpm run build:kit

      - name: Extract version from tag
        id: extract_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION"

      - name: Verify build artifacts
        run: |
          echo "Checking build artifacts..."
          ls -la packages/kit/dist/

      - name: Publish to npm
        run: pnpm publish --access public --no-git-checks --filter @nemoprotocol/wallet-kit
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
